version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rule-ai-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      target: build-stage
    container_name: rule-ai-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - backend 